### ISSUE TITLE
Entity code shows on 'Search' screen when no classes are found.

### ISSUE THREAD

**Issue by timmcallister** [jeff-mccoy/FTSS#35]
![entity code search screen](https://cloud.githubusercontent.com/assets/7793127/8273907/d2bef754-1846-11e5-8b4c-882c985fff95.png)

**Comment by jeff-mccoy** [comment]
I can't reproduce this one, I've tested on the production and local dev with Chrome & IE and don't see HTML entities.  Can you verify at your office next week?  It  may be something with your build.

**Comment by timmcallister** [comment]
Here's a screen shot from my office, it's still there:
 [image: Inline image 1]
