### ISSUE TITLE
Archive Instructor dialog doesn't dissappear after clicking 'Yes, continue'

### ISSUE THREAD

**Issue by timmcallister** [jeff-mccoy/FTSS#36]
Instructor is archived but user gets confused about whether it worked or not.
![archive instructor](https://cloud.githubusercontent.com/assets/7793127/8273926/3e237e5c-1847-11e5-8515-1a00bae957f8.png)

**Comment by jeff-mccoy** [comment]
This should have been fixed in a previous release, please let me know if it is still an issue
