### ISSUE TITLE
Instructor 'undefined' showing in create class

### ISSUE THREAD

**Issue by timmcallister** [jeff-mccoy/FTSS#42]
This is probably related to the ghost instructor showing in the production screen. I believe these are archived instructors not showing. 

![screeny](https://cloud.githubusercontent.com/assets/7793127/8814822/8b08fa5c-2fd6-11e5-8136-5986a1ce3cad.png)

**Comment by jeff-mccoy** [comment]
Is this a reproducible problem?  I can't seem to see it for your base or mine.  The instructor issue should be fixed already in the current (non-published) build.
